NAME	=	rush-02

SRC		= 	main.c ft_convert.c ft_read.c count_word.c ft_atoi.c

OBJS	=	${SRC.c:.o}

CC		=	cc -Wall -Wextra -Werror

all:		
	${CC} ${SRC} -o rush-02

clean:
			rm -f ${OBJS}
fclean:		clean
			rm -f ${NAME}
